// ========== 路径常量 ==========

// --- 缓存 ---
/// GPU 缓存文件路径
pub const CACHE_FILE_PATH: &str = "/var/cache/ftool/gpu-cache.json";

// --- PRIME 离散模式标志 ---
/// PRIME 离散模式标志文件（参考 system76-power）
pub const PRIME_DISCRETE_PATH: &str = "/etc/prime-discrete";

// --- modprobe 配置 ---
/// modprobe 配置文件路径（ftool 生成的 GPU 相关配置）
///
/// 不同模式下写入不同内容：
/// - Integrated: 黑名单所有 NVIDIA 模块
/// - Compute: 仅黑名单显示相关模块
/// - Hybrid / Nvidia: 空配置 + 追加挂起电源管理参数
pub const MODPROBE_GPU_PATH: &str = "/etc/modprobe.d/ftool-gpu.conf";

/// Integrated 模式：黑名单所有 NVIDIA 和 nouveau 驱动
pub const MODPROBE_INTEGRATED: &[u8] = br#"# Automatically generated by ftool
blacklist nouveau
blacklist nvidia
blacklist nvidia-drm
blacklist nvidia-modeset
blacklist nvidia-uvm
blacklist nvidia-current
blacklist nvidia-current-drm
blacklist nvidia-current-modeset
blacklist nvidia-current-uvm
alias nouveau off
alias nvidia off
alias nvidia-drm off
alias nvidia-modeset off
alias nvidia-uvm off
alias nvidia-current off
alias nvidia-current-drm off
alias nvidia-current-modeset off
alias nvidia-current-uvm off
"#;

/// Compute 模式：仅黑名单显示相关模块，保留 nvidia 核心驱动供计算
///
/// 注意：nvidia-uvm 未被黑名单，CUDA 计算需要此模块
/// （与 nvidia-drm/nvidia-modeset 不同，uvm 不涉及显示输出）
pub const MODPROBE_COMPUTE: &[u8] = br#"# Automatically generated by ftool
blacklist nvidia-drm
blacklist nvidia-modeset
blacklist nvidia-current-drm
blacklist nvidia-current-modeset
alias nvidia-drm off
alias nvidia-modeset off
alias nvidia-current-drm off
alias nvidia-current-modeset off
"#;

/// Hybrid / Nvidia 模式：空配置，允许所有驱动正常加载
pub const MODPROBE_EMPTY: &[u8] = br#"# Automatically generated by ftool
"#;

// --- udev 规则 ---
/// Integrated 模式：移除 NVIDIA 设备的 udev 规则路径
pub const UDEV_INTEGRATED_PATH: &str = "/etc/udev/rules.d/50-remove-nvidia.rules";

/// Integrated 模式：在 NVIDIA PCI 设备出现时自动移除
pub const UDEV_INTEGRATED: &str = r#"
# Automatically generated by ftool
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA VGA/3D controller devices
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
"#;

/// Hybrid/Compute 模式：NVIDIA 运行时电源管理 udev 规则路径
pub const UDEV_PM_PATH: &str = "/etc/udev/rules.d/80-nvidia-pm.rules";

/// Hybrid 模式：启用 NVIDIA 运行时电源管理
///
/// 包含移除 Audio/USB/UCSI 设备的规则，以在 GPU 空闲时节省电量。
pub const UDEV_PM_CONTENT: &str = r#"
# Automatically generated by ftool
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"
# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"
# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"
# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"
# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
"#;

/// Compute 模式专用：NVIDIA 运行时电源管理 udev 规则
///
/// 与 Hybrid 模式不同，Compute 模式保留 Audio/USB/UCSI 设备，
/// 因为计算工作负载可能需要 HDMI 音频输出等功能。
/// 仅对 VGA/3D 控制器执行 bind/unbind 电源管理。
pub const UDEV_PM_COMPUTE_CONTENT: &str = r#"
# Automatically generated by ftool
# Compute 模式：保留 Audio/USB/UCSI 设备，仅对 VGA/3D 控制器进行运行时电源管理
# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"
# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
"#;

// --- modeset 配置 ---
/// NVIDIA DRM modeset 配置文件路径
pub const MODESET_PATH: &str = "/etc/modprobe.d/ftool-nvidia-modeset.conf";

/// 默认 modeset 配置（nvidia 模块）
pub const MODESET_CONTENT: &str = r#"
# Automatically generated by ftool
options nvidia-drm modeset=1
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;
/// nvidia-current 模块的 modeset 配置
pub const MODESET_CURRENT_CONTENT: &str = r#"
# Automatically generated by ftool
options nvidia-current-drm modeset=1
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;

/// Compute 模式专用 modeset 配置（nvidia 模块）
///
/// Compute 模式下 nvidia-drm 已被黑名单，无需且不应配置 modeset=1，
/// 否则与 modprobe 黑名单产生语义矛盾。
pub const MODESET_COMPUTE_CONTENT: &str = r#"
# Automatically generated by ftool
# nvidia-drm 已被 Compute 模式黑名单，不需要 modeset 配置
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;
/// Compute 模式专用 modeset 配置（nvidia-current 模块）
pub const MODESET_COMPUTE_CURRENT_CONTENT: &str = r#"
# Automatically generated by ftool
# nvidia-current-drm 已被 Compute 模式黑名单，不需要 modeset 配置
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;

// --- NVIDIA 挂起/休眠电源管理 ---
/// NVIDIA 挂起相关 systemd 服务列表
pub const NVIDIA_SUSPEND_SERVICES: &[&str] = &[
    "nvidia-hibernate.service",
    "nvidia-resume.service",
    "nvidia-suspend.service",
];

/// S0ix (s2idle) 挂起模式的 modprobe 配置
pub const MODPROBE_S0IX: &[u8] = br#"# Preserve video memory through suspend
options nvidia NVreg_EnableS0ixPowerManagement=1
options nvidia-current NVreg_EnableS0ixPowerManagement=1
"#;

/// S3 (deep) 挂起模式的 modprobe 配置
pub const MODPROBE_S3: &[u8] = br#"# Preserve video memory through suspend
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia-current NVreg_PreserveVideoMemoryAllocations=1
"#;

// === NVIDIA X11 PrimaryGPU 配置 ===

/// X11 PrimaryGPU 配置文件路径
pub const XORG_CONF_NVIDIA_PATH: &str = "/etc/X11/xorg.conf.d/11-nvidia-discrete.conf";

/// X11 PrimaryGPU 配置文件备用路径（某些发行版 xorg.conf.d 位于 /usr/share 下）
/// 参考 system76-power 的 `get_xorg_conf_path` 实现。
pub const XORG_CONF_NVIDIA_FALLBACK_PATH: &str = "/usr/share/X11/xorg.conf.d/11-nvidia-discrete.conf";

/// Nvidia 离散模式 X11 PrimaryGPU 配置内容
///
/// 使 NVIDIA 成为 X11 主显示输出。ftool 仅写入 PrimaryGPU 选项，
/// 不包含 ModulePath（Fedora 上由包管理器管理 xorg 驱动路径）。
pub const XORG_CONF_NVIDIA_CONTENT: &str = r#"# Automatically generated by ftool
Section "OutputClass"
    Identifier "NVIDIA"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "PrimaryGPU" "Yes"
EndSection
"#;

// === NVIDIA 独显模式环境变量配置 ===

/// NVIDIA 独显模式环境变量配置文件路径
///
/// systemd 的 environment.d 会在用户登录时加载这些变量，
/// 确保在 Nvidia 模式下应用默认使用 NVIDIA 渲染。
pub const NV_ENV_PATH: &str = "/etc/environment.d/ftool-nvidia.conf";

/// Nvidia 模式的环境变量配置内容
///
/// - __NV_PRIME_RENDER_OFFLOAD=1: 启用 PRIME 渲染卸载
/// - __GLX_VENDOR_LIBRARY_NAME=nvidia: 指定 GLX 使用 NVIDIA 实现
/// - __VK_LAYER_NV_optimus=NVIDIA_only: 强制 Vulkan 使用 NVIDIA 专用层
/// - VK_ICD_FILENAMES=...: 指定 Vulkan 加载 NVIDIA ICD
pub const NV_ENV_CONTENT: &str = r#"# Automatically generated by ftool
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
"#;

// === NVIDIA 额外 Xorg 配置（ForceCompositionPipeline / Coolbits） ===

/// NVIDIA 额外 Xorg OutputClass 配置路径（仅 NVIDIA 模式写入）
pub const EXTRA_XORG_NVIDIA_PATH: &str = "/etc/X11/xorg.conf.d/10-ftool-nvidia-extra.conf";

/// X11 额外配置片段头部
pub const EXTRA_XORG_HEADER: &str = r#"# Automatically generated by ftool
Section "OutputClass"
    Identifier "NVIDIA Extra"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
"#;

/// ForceCompositionPipeline 选项（修复画面撕裂）
pub const EXTRA_XORG_FORCE_COMP: &str = "    Option \"ForceCompositionPipeline\" \"true\"\n";

/// Coolbits 选项模板（{} 为位掩码值）
pub const EXTRA_XORG_COOLBITS: &str = "    Option \"Coolbits\" \"{}\"\n";

/// X11 OutputClass Section 尾部
pub const EXTRA_XORG_FOOTER: &str = "EndSection\n";

// === Display Manager xrandr 桥接脚本 ===

/// SDDM Xsetup 路径（NVIDIA 模式下添加桥接脚本）
pub const SDDM_XSETUP_PATH: &str = "/usr/share/sddm/scripts/Xsetup";

/// SDDM Xsetup 备份路径
pub const SDDM_XSETUP_BAK_PATH: &str = "/usr/share/sddm/scripts/Xsetup.bak";

/// LightDM NVIDIA 桥接脚本路径
pub const LIGHTDM_SCRIPT_PATH: &str = "/etc/lightdm/ftool-nvidia.sh";

/// LightDM NVIDIA 桥接配置路径
pub const LIGHTDM_CONFIG_PATH: &str = "/etc/lightdm/lightdm.conf.d/20-ftool-nvidia.conf";

/// LightDM 配置内容
pub const LIGHTDM_CONFIG_CONTENT: &str = r#"# Automatically generated by ftool
[Seat:*]
display-setup-script=/etc/lightdm/ftool-nvidia.sh
"#;

/// NVIDIA xrandr 桥接脚本模板（{} 为 iGPU provider 名称）
pub const XRANDR_BRIDGE_SCRIPT: &str = r##"#!/bin/sh
# Automatically generated by ftool
xrandr --setprovideroutputsource "{}" NVIDIA-0
xrandr --auto
for next in $(xrandr --listmonitors | grep -E " *[0-9]+:.*" | cut -d" " -f6); do
  [ -z "$current" ] && current=$next && continue
  xrandr --output "$current" --auto --output "$next" --auto --right-of "$current"
  current=$next
done
"##;

// === 兼容旧版 EnvyControl 路径（用于清理） ===
/// 旧版 EnvyControl 的黑名单配置文件路径
pub const LEGACY_BLACKLIST_PATH: &str = "/etc/modprobe.d/blacklist-nvidia.conf";
/// 旧版 EnvyControl 的 modeset 配置文件路径
pub const LEGACY_MODESET_PATH: &str = "/etc/modprobe.d/nvidia.conf";

// === 配置快照（切换失败时回滚） ===

/// 模式切换过程中可能被清理/写入的文件列表
pub const SNAPSHOT_PATHS: &[&str] = &[
    MODPROBE_GPU_PATH,
    MODESET_PATH,
    UDEV_INTEGRATED_PATH,
    UDEV_PM_PATH,
    PRIME_DISCRETE_PATH,
    NV_ENV_PATH,
    XORG_CONF_NVIDIA_PATH,
    XORG_CONF_NVIDIA_FALLBACK_PATH,
    EXTRA_XORG_NVIDIA_PATH,
    SDDM_XSETUP_PATH,
    SDDM_XSETUP_BAK_PATH,
    LIGHTDM_SCRIPT_PATH,
    LIGHTDM_CONFIG_PATH,
    "/etc/X11/xorg.conf",
    "/etc/X11/xorg.conf.d/10-nvidia.conf",
    "/etc/X11/xorg.conf.d/90-nvidia.conf",
    "/etc/lightdm/nvidia.sh",
    "/etc/lightdm/lightdm.conf.d/20-nvidia.conf",
    "/etc/gdm/Init/Default",
    "/etc/gdm/custom.conf",
    LEGACY_BLACKLIST_PATH,
    LEGACY_MODESET_PATH,
];

/// 需要在切换前后保存/恢复状态的 systemd 服务
pub const SERVICE_SNAPSHOT_NAMES: &[&str] = &[
    "nvidia-persistenced.service",
    "nvidia-fallback.service",
    "nvidia-hibernate.service",
    "nvidia-resume.service",
    "nvidia-suspend.service",
];
