// ========== 路径常量 ==========

// --- 缓存 ---
/// GPU 缓存文件路径
pub const CACHE_FILE_PATH: &str = "/var/cache/ftool/gpu-cache.json";

// --- PRIME 离散模式标志 ---
/// PRIME 离散模式标志文件（参考 system76-power）
pub const PRIME_DISCRETE_PATH: &str = "/etc/prime-discrete";

// --- modprobe 配置 ---
/// modprobe 配置文件路径（ftool 生成的 GPU 相关配置）
///
/// 不同模式下写入不同内容：
/// - Integrated: 黑名单所有 NVIDIA 模块
/// - Compute: 仅黑名单显示相关模块
/// - Hybrid / Nvidia: 空配置 + 追加挂起电源管理参数
pub const MODPROBE_GPU_PATH: &str = "/etc/modprobe.d/ftool-gpu.conf";

/// Integrated 模式：黑名单所有 NVIDIA 和 nouveau 驱动
pub const MODPROBE_INTEGRATED: &[u8] = br#"# Automatically generated by ftool
blacklist nouveau
blacklist nvidia
blacklist nvidia-drm
blacklist nvidia-modeset
blacklist nvidia-uvm
blacklist nvidia-current
blacklist nvidia-current-drm
blacklist nvidia-current-modeset
blacklist nvidia-current-uvm
blacklist i2c-nvidia-gpu
alias nouveau off
alias nvidia off
alias nvidia-drm off
alias nvidia-modeset off
alias nvidia-uvm off
alias nvidia-current off
alias nvidia-current-drm off
alias nvidia-current-modeset off
alias nvidia-current-uvm off
alias i2c-nvidia-gpu off
"#;

/// Compute 模式：仅黑名单显示相关模块，保留 nvidia 核心驱动供计算
///
/// 注意：nvidia-uvm 未被黑名单，CUDA 计算需要此模块
/// （与 nvidia-drm/nvidia-modeset 不同，uvm 不涉及显示输出）
pub const MODPROBE_COMPUTE: &[u8] = br#"# Automatically generated by ftool
blacklist nvidia-drm
blacklist nvidia-modeset
blacklist nvidia-current-drm
blacklist nvidia-current-modeset
alias nvidia-drm off
alias nvidia-modeset off
alias nvidia-current-drm off
alias nvidia-current-modeset off
"#;

/// Hybrid / Nvidia 模式：空配置，允许所有驱动正常加载
pub const MODPROBE_EMPTY: &[u8] = br#"# Automatically generated by ftool
"#;

// --- udev 规则 ---
/// Integrated 模式：移除 NVIDIA 设备的 udev 规则路径
pub const UDEV_INTEGRATED_PATH: &str = "/etc/udev/rules.d/50-remove-nvidia.rules";

/// Integrated 模式：在 NVIDIA PCI 设备出现时自动移除
pub const UDEV_INTEGRATED: &str = r#"
# Automatically generated by ftool
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA VGA/3D controller devices
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
"#;

/// Hybrid/Compute 模式：NVIDIA 运行时电源管理 udev 规则路径
pub const UDEV_PM_PATH: &str = "/etc/udev/rules.d/80-nvidia-pm.rules";

/// Hybrid 模式：启用 NVIDIA 运行时电源管理
///
/// 包含移除 Audio/USB/UCSI 设备的规则，以在 GPU 空闲时节省电量。
pub const UDEV_PM_CONTENT: &str = r#"
# Automatically generated by ftool
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"
# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"
# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"
# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"
# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
"#;

/// Compute 模式专用：NVIDIA 运行时电源管理 udev 规则
///
/// 与 Hybrid 模式不同，Compute 模式保留 Audio/USB/UCSI 设备，
/// 因为计算工作负载可能需要 HDMI 音频输出等功能。
/// 仅对 VGA/3D 控制器执行 bind/unbind 电源管理。
pub const UDEV_PM_COMPUTE_CONTENT: &str = r#"
# Automatically generated by ftool
# Compute 模式：保留 Audio/USB/UCSI 设备，仅对 VGA/3D 控制器进行运行时电源管理
# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"
# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
"#;

// --- Xorg 配置 ---
/// Xorg 主配置文件路径
pub const XORG_PATH: &str = "/etc/X11/xorg.conf";
/// Xorg 配置目录
pub const XORG_CONF_DIR: &str = "/etc/X11/xorg.conf.d";
/// NVIDIA OutputClass 离散配置文件路径（参考 system76-power）
pub const XORG_NVIDIA_DISCRETE_CONF: &str = "/etc/X11/xorg.conf.d/11-nvidia-discrete.conf";
/// NVIDIA 额外配置路径
pub const EXTRA_XORG_PATH: &str = "/etc/X11/xorg.conf.d/10-nvidia.conf";
/// 旧版 NVIDIA 额外配置路径（用于清理）
pub const OLD_EXTRA_XORG_PATH: &str = "/etc/X11/xorg.conf.d/90-nvidia.conf";

/// Nvidia 模式专用：将 NVIDIA 设为主 GPU 的 OutputClass 配置
pub const XORG_NVIDIA_PRIMARY: &[u8] = br#"# Automatically generated by ftool
Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "PrimaryGPU" "Yes"
    ModulePath "/lib/x86_64-linux-gnu/nvidia/xorg"
EndSection
"#;
/// ForceCompositionPipeline 选项字符串
pub const FORCE_COMP: &str = "    Option \"ForceCompositionPipeline\" \"true\"\n";

// --- modeset 配置 ---
/// NVIDIA DRM modeset 配置文件路径
pub const MODESET_PATH: &str = "/etc/modprobe.d/ftool-nvidia-modeset.conf";

/// 默认 modeset 配置（nvidia 模块）
pub const MODESET_CONTENT: &str = r#"
# Automatically generated by ftool
options nvidia-drm modeset=1
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;
/// nvidia-current 模块的 modeset 配置
pub const MODESET_CURRENT_CONTENT: &str = r#"
# Automatically generated by ftool
options nvidia-current-drm modeset=1
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;

/// Compute 模式专用 modeset 配置（nvidia 模块）
///
/// Compute 模式下 nvidia-drm 已被黑名单，无需且不应配置 modeset=1，
/// 否则与 modprobe 黑名单产生语义矛盾。
pub const MODESET_COMPUTE_CONTENT: &str = r#"
# Automatically generated by ftool
# nvidia-drm 已被 Compute 模式黑名单，不需要 modeset 配置
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;
/// Compute 模式专用 modeset 配置（nvidia-current 模块）
pub const MODESET_COMPUTE_CURRENT_CONTENT: &str = r#"
# Automatically generated by ftool
# nvidia-current-drm 已被 Compute 模式黑名单，不需要 modeset 配置
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#;

// --- NVIDIA 挂起/休眠电源管理 ---
/// NVIDIA 挂起相关 systemd 服务列表
pub const NVIDIA_SUSPEND_SERVICES: &[&str] = &[
    "nvidia-hibernate.service",
    "nvidia-resume.service",
    "nvidia-suspend.service",
];

/// S0ix (s2idle) 挂起模式的 modprobe 配置
pub const MODPROBE_S0IX: &[u8] = br#"# Preserve video memory through suspend
options nvidia NVreg_EnableS0ixPowerManagement=1
options nvidia-current NVreg_EnableS0ixPowerManagement=1
"#;

/// S3 (deep) 挂起模式的 modprobe 配置
pub const MODPROBE_S3: &[u8] = br#"# Preserve video memory through suspend
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia-current NVreg_PreserveVideoMemoryAllocations=1
"#;

// --- 显示管理器 ---
/// SDDM Xsetup 脚本路径
pub const SDDM_XSETUP_PATH: &str = "/usr/share/sddm/scripts/Xsetup";
/// SDDM Xsetup 默认内容
pub const SDDM_XSETUP_CONTENT: &str =
    "#!/bin/sh\n# Xsetup - run as root before the login dialog appears\n";
/// LightDM NVIDIA 脚本路径
pub const LIGHTDM_SCRIPT_PATH: &str = "/etc/lightdm/nvidia.sh";
/// LightDM 配置文件路径
pub const LIGHTDM_CONFIG_PATH: &str = "/etc/lightdm/lightdm.conf.d/20-nvidia.conf";




// --- GDM ---
/// GDM Init 脚本路径（Fedora GDM X11 登录前的初始化脚本）
pub const GDM_INIT_PATH: &str = "/etc/gdm/Init/Default";

// === 兼容旧版 EnvyControl 路径（用于清理） ===
/// 旧版 EnvyControl 的黑名单配置文件路径
pub const LEGACY_BLACKLIST_PATH: &str = "/etc/modprobe.d/blacklist-nvidia.conf";
/// 旧版 EnvyControl 的 modeset 配置文件路径
pub const LEGACY_MODESET_PATH: &str = "/etc/modprobe.d/nvidia.conf";
