use crate::features::gpu::constants::*;

/// 系统配置文件生成器
///
/// 负责生成 Xorg、modprobe、xrandr 等系统配置文件的内容。
pub struct ConfigGenerator;

impl ConfigGenerator {
    /// 生成 Nvidia 模式的 Xorg 配置（使用 OutputClass 方式，参考 system76-power）
    pub fn generate_xorg_nvidia_primary() -> &'static [u8] {
        XORG_NVIDIA_PRIMARY
    }

    /// 生成 Nvidia 模式下的旧版完整 Xorg 配置（兼容含 ServerLayout 的传统配置）
    ///
    /// 当 `force_comp` 或 `coolbits` 有值时，对应的 Option 行直接嵌入到
    /// nvidia Device 段中，避免写入额外的配置文件造成重叠。
    pub fn generate_xorg_legacy(
        vendor: &super::detector::IgpuVendor,
        bus_id: &str,
        force_comp: bool,
        coolbits: Option<u32>,
    ) -> String {
        let (igpu_identifier, igpu_driver, screen_identifier) = match vendor {
            super::detector::IgpuVendor::Amd => ("amdgpu", "amdgpu", "amd"),
            super::detector::IgpuVendor::Intel => ("intel", "modesetting", "intel"),
        };

        let extra_opts = {
            let mut opts = String::new();
            if force_comp {
                opts.push_str(FORCE_COMP);
            }
            if let Some(val) = coolbits {
                opts.push_str(&format!("    Option \"Coolbits\" \"{}\"\n", val));
            }
            opts
        };

        format!(
            r#"
# Automatically generated by ftool
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia" Inactive "{}"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "{}"{}
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "{}"
    Driver "{}"
EndSection

Section "Screen"
    Identifier "{}"
    Device "{}"
EndSection
"#,
            igpu_identifier,
            bus_id,
            extra_opts,
            igpu_identifier,
            igpu_driver,
            screen_identifier,
            igpu_identifier
        )
    }



    /// 生成 modprobe modeset 配置文件内容
    ///
    /// 可根据需要添加 RTD3 动态电源管理参数。
    /// `use_nvidia_current` 参数控制使用 nvidia 还是 nvidia-current 内核模块。
    pub fn generate_modeset_content(rtd3: Option<u32>, use_nvidia_current: bool) -> String {
        if let Some(rtd3_val) = rtd3 {
            let hex_val = format!("0x{:02x}", rtd3_val);
            if use_nvidia_current {
                format!(
                    r#"
# Automatically generated by ftool
options nvidia-current-drm modeset=1
options nvidia-current "NVreg_DynamicPowerManagement={hex_val}"
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#
                )
            } else {
                format!(
                    r#"
# Automatically generated by ftool
options nvidia-drm modeset=1
options nvidia "NVreg_DynamicPowerManagement={hex_val}"
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"#
                )
            }
        } else if use_nvidia_current {
            MODESET_CURRENT_CONTENT.to_string()
        } else {
            MODESET_CONTENT.to_string()
        }
    }
}
