use crate::features::gpu::constants::*;

/// 系统配置文件生成器
///
/// 负责生成 modprobe、modeset 等系统配置文件的内容。
pub struct ConfigGenerator;

impl ConfigGenerator {
    /// 生成 modprobe modeset 配置文件内容
    ///
    /// 可根据需要添加 RTD3 动态电源管理参数。
    /// `use_nvidia_current` 参数控制使用 nvidia 还是 nvidia-current 内核模块。
    ///
    /// 行文本（头部/drm/页表行）来自 constants.rs 的 MODESET_*_LINE 片段
    /// （与 MODESET_CONTENT / MODESET_CURRENT_CONTENT 同源维护的唯一事实来源），
    /// 本函数在 drm 行之后按需插入 RTD3 动态电源管理行；输出与旧内联模板
    /// 逐字节一致（含开头空行），由文件末尾测试锁定。
    pub fn generate_modeset_content(rtd3: Option<u32>, use_nvidia_current: bool) -> String {
        let mut content = String::from(MODESET_HEADER_LINE);
        let (drm_line, pat_line, module) = if use_nvidia_current {
            (
                MODESET_CURRENT_DRM_LINE,
                MODESET_CURRENT_PAT_LINE,
                "nvidia-current",
            )
        } else {
            (MODESET_NVIDIA_DRM_LINE, MODESET_NVIDIA_PAT_LINE, "nvidia")
        };
        content.push_str(drm_line);
        if let Some(rtd3_val) = rtd3 {
            // RTD3 动态电源管理行紧随 drm 行之后（rtd3 取值 0-3 已在 cli 层校验，
            // 生成 0x00-0x03 两位十六进制无溢出风险）
            let hex_val = format!("0x{:02x}", rtd3_val);
            content.push_str(&format!(
                "options {module} NVreg_DynamicPowerManagement={hex_val}\n"
            ));
        }
        content.push_str(pat_line);
        content
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---------- 输出与常量模板逐字节一致 ----------

    /// WHY: 无 RTD3 时 generator 输出必须与 mod.rs nvidia 模式直接写入的
    /// MODESET_* 常量逐字节一致——两个路径写同一个配置文件，历史上存在
    /// 内联模板与常量双份维护而分叉的风险（本测试锁定两者一致）
    #[test]
    fn output_matches_constants_without_rtd3() {
        assert_eq!(
            ConfigGenerator::generate_modeset_content(None, false),
            MODESET_CONTENT
        );
        assert_eq!(
            ConfigGenerator::generate_modeset_content(None, true),
            MODESET_CURRENT_CONTENT
        );
    }

    /// WHY: RTD3 变体 = 常量模板在 drm 行后插入一行动态电源管理参数；组装
    /// 的换行/缩进若漂移会破坏 /etc/modprobe.d 文件。以下黄金字节取自重构前
    /// 内联模板原文（以空行开头、每行换行结尾是既有布局），锁定逐字节一致
    #[test]
    fn rtd3_variant_inserts_pm_line_after_drm_line() {
        let expected_nvidia = "\n# Automatically generated by ftool\noptions nvidia-drm modeset=1\noptions nvidia NVreg_DynamicPowerManagement=0x02\noptions nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0\n";
        let expected_current = "\n# Automatically generated by ftool\noptions nvidia-current-drm modeset=1\noptions nvidia-current NVreg_DynamicPowerManagement=0x02\noptions nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0\n";
        assert_eq!(
            ConfigGenerator::generate_modeset_content(Some(2), false),
            expected_nvidia
        );
        assert_eq!(
            ConfigGenerator::generate_modeset_content(Some(2), true),
            expected_current
        );
    }

    /// 边界值 0/3 的十六进制格式锁定（0x00-0x03）
    #[test]
    fn rtd3_boundary_values_format_as_two_digit_hex() {
        for (val, hex) in [(0u32, "0x00"), (3u32, "0x03")] {
            let out = ConfigGenerator::generate_modeset_content(Some(val), false);
            assert!(
                out.contains(&format!(
                    "options nvidia NVreg_DynamicPowerManagement={hex}\n"
                )),
                "应含 {hex}: {out}"
            );
        }
    }
}
