use crate::core::FtoolError;
use crate::core::runner::CommandRunner;
use crate::features::gpu::constants::*;
use crate::features::gpu::detector::{GpuDetector, SleepMode};
use crate::features::gpu::NvidiaOptions;
use log::{debug, info, warn};
use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// 原子方式写入文件：先写临时文件再 rename，确保写入原子性
///
/// 如果 `executable` 为 true，会赋予执行权限（仅限文本文件）。
/// `content` 接受字节切片，统一处理文本和二进制内容。
fn write_file_atomic(path: &str, content: &[u8], executable: bool) -> Result<(), FtoolError> {
    if let Some(parent) = Path::new(path).parent() {
        fs::create_dir_all(parent)
            .map_err(|e| FtoolError::Gpu(format!("创建目录失败 {:?}: {}", parent, e)))?;
    }

    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let tmp_path = format!("{}.tmp.{}-{}", path, std::process::id(), ts);
    fs::write(&tmp_path, content)
        .map_err(|e| FtoolError::Gpu(format!("写入临时文件失败 {}: {}", tmp_path, e)))?;
    debug!("临时文件已写入; path={}", tmp_path);

    if executable {
        let mut perms = fs::metadata(&tmp_path)
            .map_err(|e| FtoolError::Gpu(format!("获取文件元数据失败 {}: {}", tmp_path, e)))?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&tmp_path, perms)
            .map_err(|e| FtoolError::Gpu(format!("设置权限失败 {}: {}", tmp_path, e)))?;
        debug!("已赋予执行权限; path={}", tmp_path);
    }
    fs::rename(&tmp_path, path)
        .map_err(|e| {
            let _ = std::fs::remove_file(&tmp_path);
            FtoolError::Gpu(format!("重命名文件到 {} 失败: {}", path, e))
        })?;
    debug!("配置文件已生效; path={}", path);
    Ok(())
}

/// 原子方式写入文本文件（可选赋予可执行权限）
pub fn create_file(path: &str, content: &str, executable: bool) -> Result<(), FtoolError> {
    write_file_atomic(path, content.as_bytes(), executable)
}

/// 原子方式写入二进制内容文件
pub fn create_file_bytes(path: &str, content: &[u8]) -> Result<(), FtoolError> {
    write_file_atomic(path, content, false)
}

/// 清理所有由 ftool 生成的系统配置文件
pub fn cleanup() -> Result<(), FtoolError> {
    info!("🧹 清理旧的配置文件...");
    let to_remove: &[&str] = &[
        // ftool 自身生成的配置路径（仅 /etc/ 下的文件）
        MODPROBE_GPU_PATH,
        MODESET_PATH,
        UDEV_INTEGRATED_PATH,
        UDEV_PM_PATH,
        PRIME_DISCRETE_PATH,
        // NVIDIA 独显模式配置
        NV_ENV_PATH,
        EXTRA_XORG_NVIDIA_PATH,
        // 兼容旧版配置的路径（用于清理升级前的遗留文件）
        "/etc/X11/xorg.conf",
        "/etc/X11/xorg.conf.d/11-nvidia-discrete.conf",
        "/usr/share/X11/xorg.conf.d/11-nvidia-discrete.conf",
        "/etc/X11/xorg.conf.d/10-nvidia.conf",
        "/etc/X11/xorg.conf.d/90-nvidia.conf",
        "/etc/lightdm/nvidia.sh",
        "/etc/lightdm/lightdm.conf.d/20-nvidia.conf",
        LIGHTDM_SCRIPT_PATH,
        LIGHTDM_CONFIG_PATH,
        "/etc/gdm/Init/Default",
        "/etc/gdm/custom.conf",
        LEGACY_BLACKLIST_PATH,
        LEGACY_MODESET_PATH,
        // 注意：/lib/udev/rules.d/ 下的文件由包管理器管理，不在此处删除
    ];

    for path in to_remove {
        debug!("尝试删除文件; path={}", path);
        if let Err(e) = fs::remove_file(path)
            && e.kind() != std::io::ErrorKind::NotFound
        {
            warn!("无法删除文件; path={}, error={}", path, e);
        }
    }

    // 还原 SDDM Xsetup（存在备份时优先恢复原文件）
    if Path::new(SDDM_XSETUP_BAK_PATH).exists() {
        match fs::read(SDDM_XSETUP_BAK_PATH) {
            Ok(content) => {
                debug!("还原 SDDM Xsetup 备份; path={}", SDDM_XSETUP_PATH);
                write_file_atomic(SDDM_XSETUP_PATH, &content, true)?;
                fs::remove_file(SDDM_XSETUP_BAK_PATH)
                    .map_err(|e| FtoolError::Gpu(format!("删除 SDDM Xsetup 备份失败: {}", e)))?;
            }
            Err(e) => {
                warn!("读取 SDDM Xsetup 备份失败: {}", e);
            }
        }
    } else if let Ok(content) = fs::read(SDDM_XSETUP_PATH)
        && content.starts_with(b"# Automatically generated by ftool")
    {
        // 旧版本可能没有保留备份；仅删除能确认由 ftool 生成的 Xsetup
        debug!(
            "删除旧版 ftool 生成的 SDDM Xsetup; path={}",
            SDDM_XSETUP_PATH
        );
        fs::remove_file(SDDM_XSETUP_PATH)
            .map_err(|e| FtoolError::Gpu(format!("删除 SDDM Xsetup 失败: {}", e)))?;
    }

    Ok(())
}

/// 重建 initramfs（支持 dracut 和 update-initramfs，以及 OSTree 系统）
pub fn rebuild_initramfs() -> Result<(), FtoolError> {
    info!("⚙️ 正在重建 initramfs...");

    // OSTree 系系统（如 Fedora Silverblue）
    if Path::new("/ostree").exists() || Path::new("/sysroot/ostree").exists() {
        info!("检测到 OSTree 系统，使用 rpm-ostree...");
        let status =
            CommandRunner::run_status("rpm-ostree", ["initramfs", "--enable", "--arg=--force"])?;
        return CommandRunner::ensure_success(status);
    }

    // Debian/Ubuntu 使用 update-initramfs
    if Path::new("/usr/sbin/update-initramfs").exists()
        || Path::new("/sbin/update-initramfs").exists()
    {
        info!("检测到 update-initramfs，使用 Debian 方式...");
        let status = CommandRunner::run_status("update-initramfs", ["-u", "-k", "all"])?;
        return CommandRunner::ensure_success(status);
    }

    // 其他发行版使用 dracut
    let mut cmd: Vec<&str> = vec!["dracut", "--force", "--regenerate-all"];

    // 使用 systemd-inhibit 防止关机中断重建过程
    if Path::new("/usr/bin/systemd-inhibit").exists() {
        debug!("检测到 systemd-inhibit，将使用它防止关机中断重建过程");
        cmd = vec![
            "systemd-inhibit",
            "--who=ftool",
            "--why",
            "Rebuilding initramfs",
            "--",
        ]
        .into_iter()
        .chain(cmd)
        .collect();
    }

    debug!("执行命令; cmd={:?}", cmd);
    let status = CommandRunner::run_status(cmd[0], &cmd[1..])?;
    CommandRunner::ensure_success(status)
}

/// 获取 X11 配置文件路径，自动检测可用目录
///
/// 参考 system76-power 的 `get_xorg_conf_path` 实现。
pub fn get_xorg_conf_path() -> &'static str {
    if Path::new("/etc/X11/xorg.conf.d").exists() {
        XORG_CONF_NVIDIA_PATH
    } else {
        XORG_CONF_NVIDIA_FALLBACK_PATH
    }
}

/// 写入 NVIDIA 离散模式 X11 PrimaryGPU 配置
///
/// 在 Nvidia 模式下设置 PrimaryGPU "Yes"，使 NVIDIA 成为 X11 主显示输出。
/// 参考 system76-power 的 discrete 模式 Xorg 配置逻辑。
pub fn write_xorg_nvidia_config() -> Result<(), FtoolError> {
    let path = get_xorg_conf_path();
    info!("写入 X11 配置; path={}", path);
    create_file(path, XORG_CONF_NVIDIA_CONTENT, false)
}

/// 写入 NVIDIA 额外 Xorg 配置（ForceCompositionPipeline / Coolbits）
///
/// 仅在至少一个选项启用时写入。参考 gswitch 的 extra Xorg 逻辑。
pub fn write_xorg_nvidia_extra_config(opts: &NvidiaOptions) -> Result<(), FtoolError> {
    if opts.force_comp || opts.coolbits.is_some() {
        info!(
            "写入 NVIDIA 额外 Xorg 配置 (force_comp={}, coolbits={:?})",
            opts.force_comp, opts.coolbits
        );
        let mut content = String::from(EXTRA_XORG_HEADER);
        if opts.force_comp {
            content.push_str(EXTRA_XORG_FORCE_COMP);
        }
        if let Some(cb) = opts.coolbits {
            content.push_str(&EXTRA_XORG_COOLBITS.replacen("{}", &cb.to_string(), 1));
        }
        content.push_str(EXTRA_XORG_FOOTER);
        create_file(EXTRA_XORG_NVIDIA_PATH, &content, false)
    } else {
        Ok(())
    }
}

/// 写入 Display Manager xrandr 桥接脚本（SDDM / LightDM）
///
/// 在没有 MUX 切换器的笔记本上，外接显示器的物理端口通常连接到 NVIDIA GPU，
/// 需要在 DM 启动时通过 xrandr 将 iGPU 的输出桥接到 NVIDIA。参考 gswitch。
pub fn write_dm_scripts() -> Result<(), FtoolError> {
    // 检测 iGPU provider 名称
    let igpu_provider = detect_igpu_xrandr_provider();
    let script = XRANDR_BRIDGE_SCRIPT.replacen("{}", &igpu_provider, 1);

    // SDDM：必须先成功备份，再覆盖原文件，避免原 Xsetup 丢失
    if Path::new(SDDM_XSETUP_PATH).exists() {
        info!("检测到 SDDM，写入 xrandr 桥接脚本");
        let existing = fs::read_to_string(SDDM_XSETUP_PATH).map_err(|e| {
            FtoolError::Gpu(format!(
                "读取 SDDM Xsetup 失败，无法安全写入: {}",
                e
            ))
        })?;
        create_file(SDDM_XSETUP_BAK_PATH, &existing, false)?;
        create_file(SDDM_XSETUP_PATH, &script, true)?;
    }

    // LightDM
    if Path::new("/etc/lightdm").is_dir() {
        info!("检测到 LightDM，写入 xrandr 桥接脚本");
        create_file(LIGHTDM_SCRIPT_PATH, &script, true)?;
        create_file(LIGHTDM_CONFIG_PATH, LIGHTDM_CONFIG_CONTENT, false)?;
    }

    Ok(())
}

/// xrandr 检测超时时间（秒）
const XRANDR_TIMEOUT_SECS: u64 = 5;

/// 检测 iGPU 的 xrandr provider 名称
///
/// 优先取 xrandr --listproviders 中非 NVIDIA 的 provider，
/// 失败时回退到 "modesetting"（Intel/AMD 现代驱动均兼容）。
fn detect_igpu_xrandr_provider() -> String {
    if let Ok(output) =
        CommandRunner::run_with_timeout("xrandr", ["--listproviders"], XRANDR_TIMEOUT_SECS)
    {
        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            if line.contains("name:")
                && !line.contains("NVIDIA")
                && let Some(name_part) = line.split("name:").nth(1)
            {
                let name = name_part.trim();
                if !name.is_empty() {
                    debug!("检测到 iGPU xrandr provider: {}", name);
                    return name.to_string();
                }
            }
        }
    }
    "modesetting".to_string()
}

/// 写入 NVIDIA 独显模式环境变量配置
///
/// 在 Nvidia 模式下写入 /etc/environment.d/ftool-nvidia.conf，
/// 设置 __NV_PRIME_RENDER_OFFLOAD=1、__GLX_VENDOR_LIBRARY_NAME=nvidia、
/// Vulkan Optimus/ICD 环境变量，确保应用默认使用 NVIDIA 渲染。
pub fn write_nvidia_env_config() -> Result<(), FtoolError> {
    info!("写入 NVIDIA 环境变量配置; path={}", NV_ENV_PATH);
    create_file(NV_ENV_PATH, NV_ENV_CONTENT, false)
}

/// 启用或禁用 systemd 服务
///
/// 当服务操作失败时返回 `FtoolError::Process`。
/// 调用方可根据场景决定是否忽略（如 `configure_nvidia_suspend_services`）。
pub fn toggle_service(name: &str, enable: bool) -> Result<(), FtoolError> {
    let action = if enable { "enable" } else { "disable" };
    let status = CommandRunner::run_status("systemctl", [action, name])?;
    if status.success() {
        info!("已成功变更服务状态; action={}, service={}", action, name);
        Ok(())
    } else {
        Err(FtoolError::Process(format!(
            "{} {} 失败 (exit: {:?})",
            action,
            name,
            status.code()
        )))
    }
}

/// 查询 systemd 服务是否已启用
///
/// 返回 `Some(true)` 表示已启用，`Some(false)` 表示已禁用，
/// `None` 表示服务未安装或查询失败（无法用于回滚）。
pub fn service_is_enabled(name: &str) -> Option<bool> {
    let output = CommandRunner::run("systemctl", ["is-enabled", name]).ok()?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    let state = stdout.trim();
    match state {
        "enabled" | "static" => Some(true),
        "disabled" => Some(false),
        // linked/masked/indirect/not-found 等状态无法简单用 enable/disable 还原，
        // 视为“未知”，回滚时跳过。
        _ => None,
    }
}

/// 管理 NVIDIA 挂起/休眠/恢复服务的启用/禁用
///
/// 为 NVIDIA_SUSPEND_SERVICES 列表中每个服务执行 enable/disable。
/// 服务不存在或操作失败时仅记录 warn 级别日志，不会阻断流程。
pub fn configure_nvidia_suspend_services(enable: bool) -> Result<(), FtoolError> {
    for service in NVIDIA_SUSPEND_SERVICES {
        if let Err(e) = toggle_service(service, enable) {
            warn!(
                "NVIDIA 挂起服务操作失败，将忽略此错误; service={}, error={}",
                service, e
            );
        }
    }
    Ok(())
}
/// 写入 PRIME 离散模式标志文件
pub fn set_prime_discrete(mode: &str) -> Result<(), FtoolError> {
    info!("设置 {} 为 {}", PRIME_DISCRETE_PATH, mode);
    create_file(PRIME_DISCRETE_PATH, &format!("{}\n", mode), false)
}

/// 根据系统挂起模式，追加对应的 NVIDIA 电源管理配置
///
/// Integrated 模式下此函数为 no-op（不写入任何睡眠配置）。
/// 其他模式通过"读现有内容 → 合并 → 原子写"的方式写入，
/// 确保写入操作整体原子性，避免在追加写入时若崩溃导致文件损坏。
pub fn append_sleep_config(mode: super::GpuMode) -> Result<(), FtoolError> {
    if mode == super::GpuMode::Integrated {
        return Ok(());
    }

    let sleep_mode = GpuDetector::detect_sleep_mode();
    let sleep_content = match sleep_mode {
        SleepMode::S0ix => MODPROBE_S0IX,
        SleepMode::S3 => MODPROBE_S3,
        SleepMode::Unknown => {
            warn!("无法检测系统休眠模式，跳过挂起配置");
            return Ok(());
        }
    };

    let path = MODPROBE_GPU_PATH;

    // 读取现有内容（文件可能不存在）
    let existing = fs::read_to_string(path).unwrap_or_default();

    // 用关键行做精确检查，避免因空白/顺序差异误判
    let key_line = match sleep_mode {
        SleepMode::S0ix => "NVreg_EnableS0ixPowerManagement=1",
        SleepMode::S3 => "NVreg_PreserveVideoMemoryAllocations=1",
        SleepMode::Unknown => unreachable!("Unknown 已在前面返回"),
    };
    let sleep_text = String::from_utf8_lossy(sleep_content);
    if existing.contains(key_line) {
        debug!("挂起配置已存在，跳过写入");
    } else {
        // 合并内容并原子写入
        let merged = if existing.trim().is_empty()
            || existing.trim_end()
                == "# Automatically generated by ftool"
        {
            // 文件为空或只有头部注释 → 直接写入挂起配置
            format!("{}\n", sleep_text.trim())
        } else {
            // 追加到现有内容后
            format!("{}\n{}", existing.trim_end(), sleep_text.trim())
        };
        create_file(path, &merged, false)?;
    }

    // 启用 NVIDIA 挂起服务
    configure_nvidia_suspend_services(true)?;

    Ok(())
}

// ========== 运行时电源控制 ==========

/// 运行时开启 NVIDIA GPU（无需重启）
pub fn runtime_power_on() -> Result<(), FtoolError> {
    info!("⚡ 运行时开启 NVIDIA GPU...");

    // 重新扫描 PCI 总线
    fs::write("/sys/bus/pci/rescan", "1")
        .map_err(|e| FtoolError::Gpu(format!("PCI rescan 失败: {}", e)))?;

    // 同步等待后设置电源管理（参考 system76-power 的做法）
    if let Ok(pci_id) = GpuDetector::get_nvidia_raw_pci_id() {
        let mode = GpuDetector::query_current_mode();
        apply_power_control(&pci_id, mode)?;
    }

    Ok(())
}

/// 通过 PATH 环境变量查找 nvidia-smi
///
/// 除了常见的 /usr/bin，也支持容器/非标准安装位置。
fn find_nvidia_smi() -> Option<String> {
    if let Ok(paths) = std::env::var("PATH") {
        for dir in paths.split(':') {
            let full = Path::new(dir).join("nvidia-smi");
            if full.is_file() {
                return Some(full.to_string_lossy().to_string());
            }
        }
    }
    for p in &[
        "/usr/bin/nvidia-smi",
        "/usr/local/bin/nvidia-smi",
        "/usr/local/sbin/nvidia-smi",
    ] {
        if Path::new(p).is_file() {
            return Some(p.to_string());
        }
    }
    None
}

/// 检查 NVIDIA GPU 上是否有运行中的进程
///
/// 使用带超时的 run_with_timeout（5 秒），防止 nvidia-smi
/// 在驱动异常时永久阻塞。超时或执行失败均视为"无进程"。
/// 当 nvidia-smi 不可用时输出 warn 日志并跳过检查。
const NVIDIA_SMI_TIMEOUT_SECS: u64 = 5;

fn has_nvidia_processes() -> bool {
    let smi = match find_nvidia_smi() {
        Some(smi) => smi,
        None => {
            warn!("nvidia-smi 未安装，无法检测 GPU 进程状态，跳过安全检查");
            return false;
        }
    };

    let check = |args: &[&str]| -> bool {
        CommandRunner::run_with_timeout(&smi, args.iter().copied(), NVIDIA_SMI_TIMEOUT_SECS)
            .map(|output| {
                let stdout = String::from_utf8_lossy(&output.stdout);
                stdout.lines().any(|line| !line.trim().is_empty())
            })
            .unwrap_or(false)
    };

    // 检查计算类进程（CUDA、机器学习等）
    check(&[
        "--query-compute-apps=pid,process_name",
        "--format=csv,noheader",
    ])
        // 同时检查图形渲染进程（OpenGL/Vulkan 等）
        // 在 Hybrid/Nvidia 模式下可能有图形进程使用 GPU 但不被 compute-apps 列出
        || check(&[
            "--query-graphics-apps=pid,process_name",
            "--format=csv,noheader",
        ])
}

/// 运行时关闭 NVIDIA GPU（无需重启）
pub fn runtime_power_off() -> Result<(), FtoolError> {
    info!("💤 运行时关闭 NVIDIA GPU...");

    // 安全检查：确认无进程正在使用 NVIDIA GPU
    if has_nvidia_processes() {
        return Err(FtoolError::Gpu(
            "NVIDIA GPU 上存在运行中的进程，请先终止它们（如 nvidia-smi 查询结果所示）".into(),
        ));
    }

    let pci_id = match GpuDetector::get_nvidia_raw_pci_id() {
        Ok(id) => id,
        Err(_) => {
            // GPU 已不在 sysfs 中（可能已被 udev 移除或从未在线），幂等视为已关闭
            if !GpuDetector::is_nvidia_online() {
                info!("NVIDIA GPU 已处于关闭状态");
                return Ok(());
            }
            return Err(FtoolError::Gpu(
                "无法获取 NVIDIA GPU 的 PCI ID，请检查系统状态".into(),
            ));
        }
    };

    // 查找同 slot 的所有 function
    let pci_path = Path::new("/sys/bus/pci/devices");
    let slot = pci_id.split('.').next().unwrap_or("");
    let entries = fs::read_dir(pci_path)
        .map_err(|e| FtoolError::Gpu(format!("读取 PCI 设备目录失败: {}", e)))?;

    let mut functions: Vec<String> = Vec::new();
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if name_str.split('.').next().unwrap_or("") == slot {
            // 检查是否为 NVIDIA 设备
            let vendor_path = pci_path.join(name_str.as_ref()).join("vendor");
            if let Ok(vendor) = fs::read_to_string(&vendor_path)
                && vendor.trim() == "0x10de"
            {
                functions.push(name_str.into_owned());
            }
        }
    }

    // 按功能号降序排列：先解绑子设备（高功能号）再解绑父设备（功能号 0）
    functions.sort_by(|a, b| {
        let fa = a
            .split('.')
            .next_back()
            .and_then(|f| f.parse::<u32>().ok())
            .unwrap_or(0);
        let fb = b
            .split('.')
            .next_back()
            .and_then(|f| f.parse::<u32>().ok())
            .unwrap_or(0);
        fb.cmp(&fa)
    });

    // 记录已解绑设备和对应驱动，用于失败时回滚
    let mut unbound: Vec<(String, String)> = Vec::new();
    let mut errors: Vec<String> = Vec::new();

    // 步骤1：按功能号降序解绑所有 NVIDIA 设备的驱动
    for func_id in &functions {
        let func_path = pci_path.join(func_id);
        if let Ok(driver_link) = fs::read_link(func_path.join("driver")) {
            let driver_name = driver_link
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("");
            let unbind_path = format!("/sys/bus/pci/drivers/{}/unbind", driver_name);
            debug!("解绑驱动; driver={}, device={}", driver_name, func_id);
            if let Err(e) = fs::write(&unbind_path, func_id) {
                warn!(
                    "解绑 function 失败，继续处理其他 function; func={}, error={}",
                    func_id, e
                );
                errors.push(format!("解绑 {} 失败: {}", func_id, e));
            } else {
                unbound.push((func_id.clone(), driver_name.to_string()));
            }
        }
    }

    // 解绑阶段出错 → 尝试重新绑定已解绑设备 + PCI rescan 恢复
    if !errors.is_empty() {
        warn!("解绑过程出现错误，尝试恢复已解绑设备...");
        let mut rebind_failures: Vec<String> = Vec::new();
        for (func_id, driver_name) in unbound.iter().rev() {
            let bind_path = format!("/sys/bus/pci/drivers/{}/bind", driver_name);
            if let Err(e) = fs::write(&bind_path, func_id) {
                let msg = format!("恢复绑定 {} 失败: {}", func_id, e);
                warn!("{}", msg);
                rebind_failures.push(msg);
            }
        }
        // 额外尝试 PCI rescan 恢复设备
        if let Err(e) = fs::write("/sys/bus/pci/rescan", "1") {
            warn!("PCI rescan 恢复失败: {}", e);
        }
        if !rebind_failures.is_empty() {
            log::error!(
                "部分设备重绑定失败！请手动检查 lspci 状态:\n{}",
                rebind_failures.join("\n")
            );
        }
        return Err(FtoolError::Gpu(format!(
            "解绑阶段失败: {} (已尝试恢复)",
            errors.join("; ")
        )));
    }

    // 步骤2：按功能号降序从 PCI 总线移除设备
    errors.clear();
    for func_id in &functions {
        let remove_path = format!("/sys/bus/pci/devices/{}/remove", func_id);
        debug!("移除 PCI 设备; device={}", func_id);
        if let Err(e) = fs::write(&remove_path, "1") {
            warn!(
                "移除 function 失败，继续处理其他 function; func={}, error={}",
                func_id, e
            );
            errors.push(format!("移除 {} 失败: {}", func_id, e));
        }
    }

    // 移除阶段出错 → 尝试 rescan 恢复设备
    if !errors.is_empty() {
        warn!("移除过程出现错误，尝试 rescan 恢复设备...");
        if let Err(e) = fs::write("/sys/bus/pci/rescan", "1") {
            warn!("PCI rescan 恢复失败: {}", e);
        }
        return Err(FtoolError::Gpu(format!(
            "移除阶段失败: {} (已尝试 PCI rescan 恢复)",
            errors.join("; ")
        )));
    }

    Ok(())
}

/// 查询 NVIDIA GPU 电源状态（是否在线）
pub fn query_runtime_power() -> bool {
    GpuDetector::is_nvidia_online()
}

/// 轮询等待 NVIDIA 驱动绑定完成，然后设置 PCI 运行时电源管理
///
/// 参考 system76-power：NVIDIA 驱动初始化后过早修改电源管理属性
/// 可能导致系统锁死。采用轮询 + 超时机制替代固定 sleep：
/// - 先等待驱动绑定（最多 10 秒）
/// - 驱动绑定后再等待 2 秒让 NVIDIA 完成内部初始化
/// - 同步阻塞，避免后台线程因进程退出而夭折
fn apply_power_control(pci_id: &str, mode: super::GpuMode) -> Result<(), FtoolError> {
    let driver_link = format!("/sys/bus/pci/devices/{}/driver", pci_id);
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
    info!("等待 NVIDIA 驱动绑定; device={}", pci_id);
    
    let mut bound = false;
    while std::time::Instant::now() < deadline {
        if let Ok(link) = std::fs::read_link(&driver_link)
            && let Some(name) = link.file_name().and_then(|n| n.to_str())
        {
            debug!("NVIDIA 驱动已绑定; driver={}", name);
            bound = true;
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(300));
    }
    
    if !bound {
        warn!("NVIDIA 驱动未在 10 秒内绑定，仍尝试设置电源管理");
    } else {
        info!("驱动已绑定，等待内部初始化完成（2 秒）...");
        std::thread::sleep(std::time::Duration::from_secs(2));
    }

    let pm = if mode == super::GpuMode::Nvidia {
        "on\n"
    } else {
        "auto\n"
    };
    info!("设置电源管理为 {}", pm.trim());

    let control = format!("/sys/bus/pci/devices/{}/power/control", pci_id);
    let mut file = fs::OpenOptions::new()
        .create(false)
        .truncate(false)
        .write(true)
        .open(&control)
        .map_err(|e| FtoolError::Gpu(format!("打开 {} 失败: {}", control, e)))?;

    file.write_all(pm.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|e| FtoolError::Gpu(format!("设置电源管理失败: {}", e)))?;

    Ok(())
}

/// 自动设置 GPU 电源状态（基于当前模式和 runtimepm 支持判断）
///
/// 参考 system76-power 的 `auto_power` 逻辑：
/// - 非 Integrated 模式 → 开启电源
/// - Integrated 模式但 GPU 支持 runtime PM → 开启电源（允许运行时挂起省电）
/// - Integrated 模式且 GPU 不支持 runtime PM → 关闭电源
pub fn auto_power() -> Result<(), FtoolError> {
    let mode = GpuDetector::query_current_mode();
    let should_power_on = if mode == super::GpuMode::Integrated {
        // Integrated 模式下根据 runtimepm 支持决定是否保持 GPU 在线
        match GpuDetector::gpu_supports_runtimepm() {
            Ok(runtimepm) => runtimepm,
            Err(err) => {
                log::warn!("无法判断 runtimepm 支持，默认关闭 GPU 电源: {}", err);
                false
            }
        }
    } else {
        true
    };

    if should_power_on {
        runtime_power_on()
    } else if GpuDetector::is_nvidia_online() {
        runtime_power_off()
    } else {
        Ok(())
    }
}

// ========== 配置快照（切换失败时回滚） ==========

/// 单个被快照文件的内容与权限 mode
struct SnapshotFile {
    content: Vec<u8>,
    mode: u32,
}

/// 配置快照：保存一组文件内容和 systemd 服务状态，用于切换失败时恢复原状
pub struct ConfigSnapshot {
    files: HashMap<String, Option<SnapshotFile>>, // path -> file（None = 文件不存在）
    services: HashMap<String, Option<bool>>, // service -> is-enabled（None = 未知/未安装）
}

impl ConfigSnapshot {
    /// 保存指定路径列表的配置快照和服务状态
    pub fn save(paths: &[&str]) -> Result<Self, FtoolError> {
        let mut files = HashMap::new();
        for &path in paths {
            let entry = if Path::new(path).exists() {
                let metadata = fs::metadata(path).map_err(|e| {
                    FtoolError::Gpu(format!("读取快照文件元数据失败 {}: {}", path, e))
                })?;
                let content = fs::read(path).map_err(|e| {
                    FtoolError::Gpu(format!("读取快照文件失败 {}: {}", path, e))
                })?;
                let mode = metadata.permissions().mode();
                Some(SnapshotFile { content, mode })
            } else {
                None
            };
            files.insert(path.to_string(), entry);
        }
        debug!("已保存 {} 个文件的配置快照", files.len());

        let mut services = HashMap::new();
        for svc in SERVICE_SNAPSHOT_NAMES {
            services.insert(svc.to_string(), service_is_enabled(svc));
        }
        debug!("已保存 {} 个服务的状态快照", services.len());

        Ok(Self { files, services })
    }

    /// 将配置恢复到快照状态：先恢复文件，再恢复服务
    pub fn restore(&self) {
        info!("正在恢复配置快照...");

        for (path, file) in &self.files {
            match file {
                Some(file) => {
                    let executable = file.mode & 0o111 != 0;
                    match write_file_atomic(path, &file.content, executable) {
                        Ok(()) => {
                            if let Err(e) = fs::set_permissions(
                                path,
                                fs::Permissions::from_mode(file.mode),
                            ) {
                                warn!("回滚文件 {} 后恢复权限失败: {}", path, e);
                            }
                            debug!("已回滚文件: {}", path);
                        }
                        Err(e) => warn!("回滚文件 {} 失败: {}", path, e),
                    }
                }
                None => {
                    if let Err(e) = fs::remove_file(path)
                        && e.kind() != std::io::ErrorKind::NotFound
                    {
                        warn!("回滚时删除 {} 失败: {}", path, e);
                    }
                }
            }
        }

        for (svc, prev_state) in &self.services {
            match prev_state {
                Some(true) => {
                    if let Err(e) = toggle_service(svc, true) {
                        warn!("回滚服务 {} (enable) 失败: {}", svc, e);
                    }
                }
                Some(false) => {
                    if let Err(e) = toggle_service(svc, false) {
                        warn!("回滚服务 {} (disable) 失败: {}", svc, e);
                    }
                }
                None => {
                    debug!("跳过服务 {} 的回滚（快照时状态未知）", svc);
                }
            }
        }

        info!("配置快照恢复完成");
    }
}
