use crate::core::FtoolError;
use crate::core::runner::CommandRunner;
use crate::features::gpu::constants::*;
use crate::features::gpu::detector::{GpuDetector, SleepMode};
use crate::features::gpu::NvidiaOptions;
use log::{debug, info, warn};
use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// 原子方式写入文件：先写临时文件再 rename，确保写入原子性
///
/// 如果 `executable` 为 true，会赋予执行权限（仅限文本文件）。
/// `content` 接受字节切片，统一处理文本和二进制内容。
fn write_file_atomic(path: &str, content: &[u8], executable: bool) -> Result<(), FtoolError> {
    if let Some(parent) = Path::new(path).parent() {
        fs::create_dir_all(parent)
            .map_err(|e| FtoolError::Gpu(format!("创建目录失败 {:?}: {}", parent, e)))?;
    }

    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let tmp_path = format!("{}.tmp.{}-{}", path, std::process::id(), ts);
    fs::write(&tmp_path, content).map_err(|e| {
        let _ = std::fs::remove_file(&tmp_path); // 清理可能残留的临时文件
        FtoolError::Gpu(format!("写入临时文件失败 {}: {}", tmp_path, e))
    })?;
    debug!("临时文件已写入; path={}", tmp_path);

    // 显式设置权限，避免结果受进程 umask 影响：可执行文件 0755，普通配置文件 0644
    let mut perms = fs::metadata(&tmp_path)
        .map_err(|e| FtoolError::Gpu(format!("获取文件元数据失败 {}: {}", tmp_path, e)))?
        .permissions();
    perms.set_mode(if executable { 0o755 } else { 0o644 });
    fs::set_permissions(&tmp_path, perms)
        .map_err(|e| FtoolError::Gpu(format!("设置权限失败 {}: {}", tmp_path, e)))?;
    debug!("已设置文件权限; path={}, executable={}", tmp_path, executable);
    fs::rename(&tmp_path, path)
        .map_err(|e| {
            let _ = std::fs::remove_file(&tmp_path);
            FtoolError::Gpu(format!("重命名文件到 {} 失败: {}", path, e))
        })?;
    debug!("配置文件已生效; path={}", path);
    Ok(())
}

/// 原子方式写入文本文件（可选赋予可执行权限）
pub fn create_file(path: &str, content: &str, executable: bool) -> Result<(), FtoolError> {
    write_file_atomic(path, content.as_bytes(), executable)
}

/// 原子方式写入二进制内容文件
pub fn create_file_bytes(path: &str, content: &[u8]) -> Result<(), FtoolError> {
    write_file_atomic(path, content, false)
}

/// 清理所有由 ftool 生成的系统配置文件
pub fn cleanup() -> Result<(), FtoolError> {
    info!("🧹 清理旧的配置文件...");
    // ftool 自身生成的配置路径（仅 /etc/ 下的文件，文件名即所有权，直接删除）
    let to_remove: &[&str] = &[
        MODPROBE_GPU_PATH,
        MODESET_PATH,
        UDEV_INTEGRATED_PATH,
        UDEV_PM_PATH,
        PRIME_DISCRETE_PATH,
        // NVIDIA 独显模式配置
        NV_ENV_PATH,
        EXTRA_XORG_NVIDIA_PATH,
        XORG_CONF_NVIDIA_PATH,
        LIGHTDM_SCRIPT_PATH,
        LIGHTDM_CONFIG_PATH,
        // 注意：/lib/udev/rules.d/ 下的文件由包管理器管理，不在此处删除
    ];

    for path in to_remove {
        debug!("尝试删除文件; path={}", path);
        if let Err(e) = fs::remove_file(path)
            && e.kind() != std::io::ErrorKind::NotFound
        {
            warn!("无法删除文件; path={}, error={}", path, e);
        }
    }

    // 旧版兼容路径（用于清理升级前的遗留文件）：
    // 这些文件名并非 ftool 专有，可能由用户手写或 nvidia-xconfig 等第三方工具生成，
    // 因此仅当内容确认带 ftool 生成标记时才删除，防止误删用户自己的配置
    // （切换成功的路径不会触发快照回滚，删除是不可逆的）。
    const FTOOL_MARKER: &str = "# Automatically generated by ftool";
    let legacy_paths: &[&str] = &[
        "/etc/X11/xorg.conf",
        "/usr/share/X11/xorg.conf.d/11-nvidia-discrete.conf",
        "/etc/X11/xorg.conf.d/10-nvidia.conf",
        "/etc/X11/xorg.conf.d/90-nvidia.conf",
        "/etc/lightdm/nvidia.sh",
        "/etc/lightdm/lightdm.conf.d/20-nvidia.conf",
        "/etc/gdm/Init/Default",
        "/etc/gdm/custom.conf",
        LEGACY_BLACKLIST_PATH,
        LEGACY_MODESET_PATH,
    ];

    for path in legacy_paths {
        match fs::read_to_string(path) {
            Ok(content) if content.contains(FTOOL_MARKER) => {
                debug!("删除旧版 ftool 生成的遗留文件; path={}", path);
                if let Err(e) = fs::remove_file(path)
                    && e.kind() != std::io::ErrorKind::NotFound
                {
                    warn!("无法删除文件; path={}, error={}", path, e);
                }
            }
            Ok(_) => {
                warn!(
                    "跳过删除 {}: 文件存在但内容不含 ftool 生成标记，可能为用户自建配置",
                    path
                );
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                // 文件不存在，无需处理
            }
            Err(e) => {
                warn!("读取 {} 失败，跳过删除: {}", path, e);
            }
        }
    }

    // 还原 SDDM Xsetup（存在备份时优先恢复原文件）
    if Path::new(SDDM_XSETUP_BAK_PATH).exists() {
        match fs::read(SDDM_XSETUP_BAK_PATH) {
            Ok(content) => {
                debug!("还原 SDDM Xsetup 备份; path={}", SDDM_XSETUP_PATH);
                write_file_atomic(SDDM_XSETUP_PATH, &content, true)?;
                fs::remove_file(SDDM_XSETUP_BAK_PATH)
                    .map_err(|e| FtoolError::Gpu(format!("删除 SDDM Xsetup 备份失败: {}", e)))?;
            }
            Err(e) => {
                warn!("读取 SDDM Xsetup 备份失败: {}", e);
            }
        }
    } else if let Ok(content) = fs::read(SDDM_XSETUP_PATH)
        && content.starts_with(b"# Automatically generated by ftool")
    {
        // 旧版本可能没有保留备份；仅删除能确认由 ftool 生成的 Xsetup
        debug!(
            "删除旧版 ftool 生成的 SDDM Xsetup; path={}",
            SDDM_XSETUP_PATH
        );
        fs::remove_file(SDDM_XSETUP_PATH)
            .map_err(|e| FtoolError::Gpu(format!("删除 SDDM Xsetup 失败: {}", e)))?;
    }

    Ok(())
}

/// 重建 initramfs（支持 dracut 和 update-initramfs，以及 OSTree 系统）
pub fn rebuild_initramfs() -> Result<(), FtoolError> {
    info!("⚙️ 正在重建 initramfs...");

    // OSTree 系系统（如 Fedora Silverblue）
    if Path::new("/ostree").exists() || Path::new("/sysroot/ostree").exists() {
        info!("检测到 OSTree 系统，使用 rpm-ostree...");
        let status =
            CommandRunner::run_status("rpm-ostree", ["initramfs", "--enable", "--arg=--force"])?;
        return CommandRunner::ensure_success(status);
    }

    // Debian/Ubuntu 使用 update-initramfs
    if Path::new("/usr/sbin/update-initramfs").exists()
        || Path::new("/sbin/update-initramfs").exists()
    {
        info!("检测到 update-initramfs，使用 Debian 方式...");
        let status = CommandRunner::run_status("update-initramfs", ["-u", "-k", "all"])?;
        return CommandRunner::ensure_success(status);
    }

    // 其他发行版使用 dracut
    let mut cmd: Vec<&str> = vec!["dracut", "--force", "--regenerate-all"];

    // 使用 systemd-inhibit 防止关机中断重建过程
    if Path::new("/usr/bin/systemd-inhibit").exists() {
        debug!("检测到 systemd-inhibit，将使用它防止关机中断重建过程");
        cmd = vec![
            "systemd-inhibit",
            "--who=ftool",
            "--why",
            "Rebuilding initramfs",
            "--",
        ]
        .into_iter()
        .chain(cmd)
        .collect();
    }

    debug!("执行命令; cmd={:?}", cmd);
    let status = CommandRunner::run_status(cmd[0], &cmd[1..])?;
    CommandRunner::ensure_success(status)
}

/// 获取 X11 配置文件路径，自动检测可用目录
///
/// 参考 system76-power 的 `get_xorg_conf_path` 实现。
pub fn get_xorg_conf_path() -> &'static str {
    if Path::new("/etc/X11/xorg.conf.d").exists() {
        XORG_CONF_NVIDIA_PATH
    } else {
        XORG_CONF_NVIDIA_FALLBACK_PATH
    }
}

/// 写入 NVIDIA 离散模式 X11 PrimaryGPU 配置
///
/// 在 Nvidia 模式下设置 PrimaryGPU "Yes"，使 NVIDIA 成为 X11 主显示输出。
/// 参考 system76-power 的 discrete 模式 Xorg 配置逻辑。
pub fn write_xorg_nvidia_config() -> Result<(), FtoolError> {
    let path = get_xorg_conf_path();
    info!("写入 X11 配置; path={}", path);
    create_file(path, XORG_CONF_NVIDIA_CONTENT, false)
}

/// 写入 NVIDIA 额外 Xorg 配置（ForceCompositionPipeline / Coolbits）
///
/// 仅在至少一个选项启用时写入。参考 gswitch 的 extra Xorg 逻辑。
pub fn write_xorg_nvidia_extra_config(opts: &NvidiaOptions) -> Result<(), FtoolError> {
    if opts.force_comp || opts.coolbits.is_some() {
        info!(
            "写入 NVIDIA 额外 Xorg 配置 (force_comp={}, coolbits={:?})",
            opts.force_comp, opts.coolbits
        );
        let mut content = String::from(EXTRA_XORG_HEADER);
        if opts.force_comp {
            content.push_str(EXTRA_XORG_FORCE_COMP);
        }
        if let Some(cb) = opts.coolbits {
            content.push_str(&EXTRA_XORG_COOLBITS.replacen("{}", &cb.to_string(), 1));
        }
        content.push_str(EXTRA_XORG_FOOTER);
        create_file(EXTRA_XORG_NVIDIA_PATH, &content, false)
    } else {
        Ok(())
    }
}

/// 写入 Display Manager xrandr 桥接脚本（SDDM / LightDM）
///
/// 在没有 MUX 切换器的笔记本上，外接显示器的物理端口通常连接到 NVIDIA GPU，
/// 需要在 DM 启动时通过 xrandr 将 iGPU 的输出桥接到 NVIDIA。参考 gswitch。
pub fn write_dm_scripts() -> Result<(), FtoolError> {
    // 检测 iGPU provider 名称
    let igpu_provider = detect_igpu_xrandr_provider();
    let script = XRANDR_BRIDGE_SCRIPT.replacen("{}", &igpu_provider, 1);

    // SDDM：必须先成功备份，再覆盖原文件，避免原 Xsetup 丢失
    if Path::new(SDDM_XSETUP_PATH).exists() {
        info!("检测到 SDDM，写入 xrandr 桥接脚本");
        let existing = fs::read_to_string(SDDM_XSETUP_PATH).map_err(|e| {
            FtoolError::Gpu(format!(
                "读取 SDDM Xsetup 失败，无法安全写入: {}",
                e
            ))
        })?;
        create_file(SDDM_XSETUP_BAK_PATH, &existing, false)?;
        create_file(SDDM_XSETUP_PATH, &script, true)?;
    }

    // LightDM
    if Path::new("/etc/lightdm").is_dir() {
        info!("检测到 LightDM，写入 xrandr 桥接脚本");
        create_file(LIGHTDM_SCRIPT_PATH, &script, true)?;
        create_file(LIGHTDM_CONFIG_PATH, LIGHTDM_CONFIG_CONTENT, false)?;
    }

    Ok(())
}

/// xrandr 检测超时时间（秒）
const XRANDR_TIMEOUT_SECS: u64 = 5;

/// 检测 iGPU 的 xrandr provider 名称
///
/// 优先取 xrandr --listproviders 中非 NVIDIA 的 provider，
/// 失败时回退到 "modesetting"（Intel/AMD 现代驱动均兼容）。
fn detect_igpu_xrandr_provider() -> String {
    if let Ok(output) =
        CommandRunner::run_with_timeout("xrandr", ["--listproviders"], XRANDR_TIMEOUT_SECS)
    {
        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            if line.contains("name:")
                && !line.contains("NVIDIA")
                && let Some(name_part) = line.split("name:").nth(1)
            {
                let name = name_part.trim();
                if !name.is_empty() {
                    debug!("检测到 iGPU xrandr provider: {}", name);
                    return name.to_string();
                }
            }
        }
    }
    "modesetting".to_string()
}

/// 写入 NVIDIA 独显模式环境变量配置
///
/// 在 Nvidia 模式下写入 /etc/environment.d/ftool-nvidia.conf，
/// 设置 __NV_PRIME_RENDER_OFFLOAD=1、__GLX_VENDOR_LIBRARY_NAME=nvidia、
/// Vulkan Optimus/ICD 环境变量，确保应用默认使用 NVIDIA 渲染。
pub fn write_nvidia_env_config() -> Result<(), FtoolError> {
    info!("写入 NVIDIA 环境变量配置; path={}", NV_ENV_PATH);
    create_file(NV_ENV_PATH, NV_ENV_CONTENT, false)
}

/// 启用或禁用 systemd 服务
///
/// 当服务操作失败时返回 `FtoolError::Process`。
/// 调用方可根据场景决定是否忽略（如 `configure_nvidia_suspend_services`）。
pub fn toggle_service(name: &str, enable: bool) -> Result<(), FtoolError> {
    let action = if enable { "enable" } else { "disable" };
    let status = CommandRunner::run_status("systemctl", [action, name])?;
    if status.success() {
        info!("已成功变更服务状态; action={}, service={}", action, name);
        Ok(())
    } else {
        Err(FtoolError::Process(format!(
            "{} {} 失败 (exit: {:?})",
            action,
            name,
            status.code()
        )))
    }
}

/// 查询 systemd 服务是否已启用
///
/// 返回 `Some(true)` 表示已启用，`Some(false)` 表示已禁用，
/// `None` 表示服务未安装或查询失败（无法用于回滚）。
pub fn service_is_enabled(name: &str) -> Option<bool> {
    let output = CommandRunner::run("systemctl", ["is-enabled", name]).ok()?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    let state = stdout.trim();
    match state {
        "enabled" | "static" => Some(true),
        "disabled" => Some(false),
        // linked/masked/indirect/not-found 等状态无法简单用 enable/disable 还原，
        // 视为“未知”，回滚时跳过。
        _ => None,
    }
}

/// 管理 NVIDIA 挂起/休眠/恢复服务的启用/禁用
///
/// 为 NVIDIA_SUSPEND_SERVICES 列表中每个服务执行 enable/disable。
/// 服务不存在或操作失败时仅记录 warn 级别日志，不会阻断流程。
pub fn configure_nvidia_suspend_services(enable: bool) -> Result<(), FtoolError> {
    for service in NVIDIA_SUSPEND_SERVICES {
        if let Err(e) = toggle_service(service, enable) {
            warn!(
                "NVIDIA 挂起服务操作失败，将忽略此错误; service={}, error={}",
                service, e
            );
        }
    }
    Ok(())
}
/// 写入 PRIME 离散模式标志文件
pub fn set_prime_discrete(mode: &str) -> Result<(), FtoolError> {
    info!("设置 {} 为 {}", PRIME_DISCRETE_PATH, mode);
    create_file(PRIME_DISCRETE_PATH, &format!("{}\n", mode), false)
}

/// 根据系统挂起模式，追加对应的 NVIDIA 电源管理配置
///
/// Integrated 模式下此函数为 no-op（不写入任何睡眠配置）。
/// 其他模式通过"读现有内容 → 合并 → 原子写"的方式写入，
/// 确保写入操作整体原子性，避免在追加写入时若崩溃导致文件损坏。
pub fn append_sleep_config(mode: super::GpuMode) -> Result<(), FtoolError> {
    if mode == super::GpuMode::Integrated {
        return Ok(());
    }

    let sleep_mode = GpuDetector::detect_sleep_mode();
    let sleep_content = match sleep_mode {
        SleepMode::S0ix => MODPROBE_S0IX,
        SleepMode::S3 => MODPROBE_S3,
        SleepMode::Unknown => {
            warn!("无法检测系统休眠模式，跳过挂起配置");
            return Ok(());
        }
    };

    let path = MODPROBE_GPU_PATH;

    // 读取现有内容（文件可能不存在）
    let mut existing = fs::read_to_string(path).unwrap_or_default();

    // 用关键行做精确检查，避免因空白/顺序差异误判
    let (key_line, other_key) = match sleep_mode {
        SleepMode::S0ix => (
            "NVreg_EnableS0ixPowerManagement=1",
            "NVreg_PreserveVideoMemoryAllocations=1",
        ),
        SleepMode::S3 => (
            "NVreg_PreserveVideoMemoryAllocations=1",
            "NVreg_EnableS0ixPowerManagement=1",
        ),
        SleepMode::Unknown => unreachable!("Unknown 已在前面返回"),
    };

    // S0ix 与 S3 两种挂起参数不可并存：先剔除另一种模式的参数行，
    // 避免系统挂起方式变更后两份 options 同时生效（行为取决于驱动解析顺序）
    existing = existing
        .lines()
        .filter(|l| !l.contains(other_key))
        .collect::<Vec<_>>()
        .join("\n");

    let sleep_text = String::from_utf8_lossy(sleep_content);
    if existing.contains(key_line) {
        debug!("挂起配置已存在，跳过写入");
    } else {
        // 合并内容并原子写入（保留 ftool 生成标记头，便于识别与后续清理）
        const HEADER: &str = "# Automatically generated by ftool";
        let merged = if existing.trim().is_empty() || existing.trim_end() == HEADER {
            format!("{}\n{}\n", HEADER, sleep_text.trim())
        } else {
            format!("{}\n{}\n", existing.trim_end(), sleep_text.trim())
        };
        create_file(path, &merged, false)?;
    }

    // 注意：本函数只负责写入挂起参数，不管理 NVIDIA 挂起服务的启停——
    // 服务状态统一由 mod.rs 的 configure_gpu_services 按模式决定
    // （各模式的启停策略见 mod.rs 中 configure_gpu_services 的调用点），避免此处无条件启用与模式策略相矛盾。

    Ok(())
}

// ========== 运行时电源控制 ==========

/// 运行时开启 NVIDIA GPU（无需重启）
pub fn runtime_power_on() -> Result<(), FtoolError> {
    info!("⚡ 运行时开启 NVIDIA GPU...");

    // 重新扫描 PCI 总线，让被移除/未枚举的 NVIDIA 设备重新出现
    fs::write("/sys/bus/pci/rescan", "1")
        .map_err(|e| FtoolError::Gpu(format!("PCI rescan 失败: {}", e)))?;

    // rescan 由内核异步完成枚举，轮询等待 NVIDIA GPU 重新出现在 sysfs 中，
    // 不再静默吞掉检测失败（否则会向用户报告成功而 GPU 实际未开启）
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
    let pci_id = loop {
        if let Ok(id) = GpuDetector::get_nvidia_raw_pci_id() {
            break id;
        }
        if std::time::Instant::now() >= deadline {
            let hint = if Path::new(UDEV_INTEGRATED_PATH).exists() {
                "；注意当前存在 integrated 模式的 udev 移除规则，设备出现后会被再次移除，无法保持开启"
            } else {
                ""
            };
            return Err(FtoolError::Gpu(format!(
                "PCI rescan 后 10 秒内未检测到 NVIDIA GPU{}",
                hint
            )));
        }
        std::thread::sleep(std::time::Duration::from_millis(300));
    };

    // 等驱动绑定完成后设置电源管理（参考 system76-power 的做法）
    let mode = GpuDetector::query_current_mode();
    apply_power_control(&pci_id, mode)?;
    Ok(())
}

/// 通过扫描 /proc/<pid>/fd 检测正在使用 NVIDIA GPU 的进程
///
/// NVIDIA 用户态驱动（CUDA/GLX/Vulkan）通过打开 /dev/nvidia* 字符设备
/// 与内核驱动交互；nvidia-drm 显示路径则打开 /dev/dri/cardN|renderDN。
/// 直接扫描进程 fd 即可发现 GPU 使用者，不依赖 nvidia-smi
/// （该工具并非所有安装场景都存在）。
///
/// 以 root 运行时才能读取其他进程的 fd；个别进程读取失败（权限不足或
/// 恰好退出）视为无 GPU 使用，予以跳过。nvidia-persistenced 服务为保持
/// GPU 初始化而常驻持有 /dev/nvidiactl，不计入"运行中的进程"。
fn has_nvidia_processes() -> Result<bool, FtoolError> {
    let proc_dir = Path::new("/proc");
    let entries = fs::read_dir(proc_dir)
        .map_err(|e| FtoolError::Gpu(format!("无法读取 /proc: {}", e)))?;

    for entry in entries.flatten() {
        let pid = entry.file_name();
        let pid_str = pid.to_string_lossy();
        if !pid_str.chars().all(|c| c.is_ascii_digit()) {
            continue;
        }

        // nvidia-persistenced 常驻持有 /dev/nvidiactl，不代表运行中的工作负载
        let comm = fs::read_to_string(proc_dir.join(&pid).join("comm")).unwrap_or_default();
        if comm.trim() == "nvidia-persistenced" {
            continue;
        }

        let fd_dir = entry.path().join("fd");
        let Ok(fds) = fs::read_dir(&fd_dir) else {
            // 进程已退出或权限不足（root 下通常可读），跳过该进程
            continue;
        };
        for fd in fds.flatten() {
            let Ok(target) = fs::read_link(fd.path()) else {
                continue;
            };
            if fd_target_is_nvidia(&target.to_string_lossy()) {
                return Ok(true);
            }
        }
    }
    Ok(false)
}

/// 判断文件描述符目标是否为 NVIDIA GPU 设备节点
///
/// - `/dev/nvidia*`（nvidiactl / nvidia0 / nvidia-uvm / nvidia-modeset 等）直接命中；
/// - `/dev/dri/cardN|renderDN` 需经 sysfs 确认其 PCI vendor 为 NVIDIA
///   （同一系统中的 DRM 节点也可能来自 Intel/AMD 核显）。
fn fd_target_is_nvidia(target: &str) -> bool {
    if target.starts_with("/dev/nvidia") {
        return true;
    }
    let Some(name) = target.strip_prefix("/dev/dri/") else {
        return false;
    };
    if !(name.starts_with("card") || name.starts_with("renderD")) {
        return false;
    }
    let vendor_path = Path::new("/sys/class/drm").join(name).join("device/vendor");
    fs::read_to_string(vendor_path)
        .map(|v| v.trim() == "0x10de")
        .unwrap_or(false)
}

/// 运行时关闭 NVIDIA GPU（无需重启）
pub fn runtime_power_off() -> Result<(), FtoolError> {
    info!("💤 运行时关闭 NVIDIA GPU...");

    // 门禁 1：Nvidia 模式下 NVIDIA 正驱动显示输出，运行时关闭会把主显示热移除
    if GpuDetector::query_current_mode() == super::GpuMode::Nvidia {
        return Err(FtoolError::Gpu(
            "当前处于 nvidia 模式（NVIDIA 正驱动显示输出），禁止运行时关闭 GPU；\
             请先切换到其他模式并重启后再执行"
                .into(),
        ));
    }

    // 门禁 2：确认无进程正在使用 NVIDIA GPU（无法确认时检查函数报错，不静默放行）
    if has_nvidia_processes()? {
        return Err(FtoolError::Gpu(
            "NVIDIA GPU 上存在运行中的进程，请先终止它们（如 nvidia-smi 查询结果所示）".into(),
        ));
    }

    let pci_id = match GpuDetector::get_nvidia_raw_pci_id() {
        Ok(id) => id,
        Err(_) => {
            // GPU 已不在 sysfs 中（可能已被 udev 移除或从未在线），幂等视为已关闭
            if !GpuDetector::is_nvidia_online() {
                info!("NVIDIA GPU 已处于关闭状态");
                return Ok(());
            }
            return Err(FtoolError::Gpu(
                "无法获取 NVIDIA GPU 的 PCI ID，请检查系统状态".into(),
            ));
        }
    };

    // 查找同 slot 的所有 function
    let pci_path = Path::new("/sys/bus/pci/devices");
    let slot = pci_id.split('.').next().unwrap_or("");
    let entries = fs::read_dir(pci_path)
        .map_err(|e| FtoolError::Gpu(format!("读取 PCI 设备目录失败: {}", e)))?;

    let mut functions: Vec<String> = Vec::new();
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if name_str.split('.').next().unwrap_or("") == slot {
            // 检查是否为 NVIDIA 设备
            let vendor_path = pci_path.join(name_str.as_ref()).join("vendor");
            if let Ok(vendor) = fs::read_to_string(&vendor_path)
                && vendor.trim() == "0x10de"
            {
                functions.push(name_str.into_owned());
            }
        }
    }

    // 按功能号降序排列：先解绑子设备（高功能号）再解绑父设备（功能号 0）
    functions.sort_by(|a, b| {
        let fa = a
            .split('.')
            .next_back()
            .and_then(|f| f.parse::<u32>().ok())
            .unwrap_or(0);
        let fb = b
            .split('.')
            .next_back()
            .and_then(|f| f.parse::<u32>().ok())
            .unwrap_or(0);
        fb.cmp(&fa)
    });

    // 记录已解绑设备和对应驱动，用于失败时回滚
    let mut unbound: Vec<(String, String)> = Vec::new();
    let mut errors: Vec<String> = Vec::new();

    // 步骤1：按功能号降序解绑所有 NVIDIA 设备的驱动
    for func_id in &functions {
        let func_path = pci_path.join(func_id);
        if let Ok(driver_link) = fs::read_link(func_path.join("driver")) {
            let driver_name = driver_link
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("");
            let unbind_path = format!("/sys/bus/pci/drivers/{}/unbind", driver_name);
            debug!("解绑驱动; driver={}, device={}", driver_name, func_id);
            if let Err(e) = fs::write(&unbind_path, func_id) {
                warn!(
                    "解绑 function 失败，继续处理其他 function; func={}, error={}",
                    func_id, e
                );
                errors.push(format!("解绑 {} 失败: {}", func_id, e));
            } else {
                unbound.push((func_id.clone(), driver_name.to_string()));
            }
        }
    }

    // 解绑阶段出错 → 尝试重新绑定已解绑设备 + PCI rescan 恢复
    if !errors.is_empty() {
        warn!("解绑过程出现错误，尝试恢复已解绑设备...");
        let mut rebind_failures: Vec<String> = Vec::new();
        for (func_id, driver_name) in unbound.iter().rev() {
            let bind_path = format!("/sys/bus/pci/drivers/{}/bind", driver_name);
            if let Err(e) = fs::write(&bind_path, func_id) {
                let msg = format!("恢复绑定 {} 失败: {}", func_id, e);
                warn!("{}", msg);
                rebind_failures.push(msg);
            }
        }
        // 额外尝试 PCI rescan 恢复设备
        if let Err(e) = fs::write("/sys/bus/pci/rescan", "1") {
            warn!("PCI rescan 恢复失败: {}", e);
        }
        if !rebind_failures.is_empty() {
            log::error!(
                "部分设备重绑定失败！请手动检查 lspci 状态:\n{}",
                rebind_failures.join("\n")
            );
        }
        return Err(FtoolError::Gpu(format!(
            "解绑阶段失败: {} (已尝试恢复)",
            errors.join("; ")
        )));
    }

    // 步骤2：按功能号降序从 PCI 总线移除设备
    errors.clear();
    for func_id in &functions {
        let remove_path = format!("/sys/bus/pci/devices/{}/remove", func_id);
        debug!("移除 PCI 设备; device={}", func_id);
        if let Err(e) = fs::write(&remove_path, "1") {
            warn!(
                "移除 function 失败，继续处理其他 function; func={}, error={}",
                func_id, e
            );
            errors.push(format!("移除 {} 失败: {}", func_id, e));
        }
    }

    // 移除阶段出错 → 尝试 rescan 恢复设备
    if !errors.is_empty() {
        warn!("移除过程出现错误，尝试 rescan 恢复设备...");
        if let Err(e) = fs::write("/sys/bus/pci/rescan", "1") {
            warn!("PCI rescan 恢复失败: {}", e);
        }
        return Err(FtoolError::Gpu(format!(
            "移除阶段失败: {} (已尝试 PCI rescan 恢复)",
            errors.join("; ")
        )));
    }

    Ok(())
}

/// 查询 NVIDIA GPU 电源状态（是否在线）
pub fn query_runtime_power() -> bool {
    GpuDetector::is_nvidia_online()
}

/// 轮询等待 NVIDIA 驱动绑定完成，然后设置 PCI 运行时电源管理
///
/// 参考 system76-power：NVIDIA 驱动初始化后过早修改电源管理属性
/// 可能导致系统锁死。采用轮询 + 超时机制替代固定 sleep：
/// - 先等待驱动绑定（最多 10 秒）
/// - 驱动绑定后再等待 2 秒让 NVIDIA 完成内部初始化
/// - 同步阻塞，避免后台线程因进程退出而夭折
fn apply_power_control(pci_id: &str, mode: super::GpuMode) -> Result<(), FtoolError> {
    let driver_link = format!("/sys/bus/pci/devices/{}/driver", pci_id);
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
    info!("等待 NVIDIA 驱动绑定; device={}", pci_id);
    
    let mut bound = false;
    while std::time::Instant::now() < deadline {
        if let Ok(link) = std::fs::read_link(&driver_link)
            && let Some(name) = link.file_name().and_then(|n| n.to_str())
        {
            debug!("NVIDIA 驱动已绑定; driver={}", name);
            bound = true;
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(300));
    }
    
    if !bound {
        warn!("NVIDIA 驱动未在 10 秒内绑定，仍尝试设置电源管理");
    } else {
        info!("驱动已绑定，等待内部初始化完成（2 秒）...");
        std::thread::sleep(std::time::Duration::from_secs(2));
    }

    let pm = if mode == super::GpuMode::Nvidia {
        "on\n"
    } else {
        "auto\n"
    };
    info!("设置电源管理为 {}", pm.trim());

    let control = format!("/sys/bus/pci/devices/{}/power/control", pci_id);
    let mut file = fs::OpenOptions::new()
        .create(false)
        .truncate(false)
        .write(true)
        .open(&control)
        .map_err(|e| FtoolError::Gpu(format!("打开 {} 失败: {}", control, e)))?;

    file.write_all(pm.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|e| FtoolError::Gpu(format!("设置电源管理失败: {}", e)))?;

    Ok(())
}

/// 自动设置 GPU 电源状态（基于当前模式和 runtimepm 支持判断）
/// 参考 system76-power 的 `auto_power` 逻辑，并按 ftool 的 integrated
/// 实现做了修正：ftool 的 integrated 模式通过 udev 规则物理移除 NVIDIA
/// 设备——设备已不在线时不应再尝试"开启"（rescan 复活后会被移除规则
/// 再次移除，形成竞态且毫无意义），此时保持现状即可。
/// - 非 Integrated 模式 → 开启电源
/// - Integrated 模式且 GPU 在线：支持 runtime PM → 保持在线（空闲自动挂起省电）
/// - Integrated 模式且 GPU 在线：不支持 runtime PM → 关闭电源（与 udev 移除规则目的一致）
/// - Integrated 模式且 GPU 不在线（已被 udev 规则移除）→ 无需操作
pub fn auto_power() -> Result<(), FtoolError> {
    let mode = GpuDetector::query_current_mode();
    if mode == super::GpuMode::Integrated {
        // GPU 已不在线（integrated 的 udev 规则已物理移除它）：保持现状
        if !GpuDetector::is_nvidia_online() {
            info!("Integrated 模式下 NVIDIA GPU 已被移除/不在线，无需电源操作");
            return Ok(());
        }
        // GPU 仍在线：按 runtimepm 支持决定保持在线（空闲自动挂起）还是关闭
        match GpuDetector::gpu_supports_runtimepm() {
            Ok(true) => runtime_power_on(),
            Ok(false) => runtime_power_off(),
            Err(err) => {
                log::warn!("无法判断 runtimepm 支持，按不支持处理: {}", err);
                runtime_power_off()
            }
        }
    } else {
        runtime_power_on()
    }
}

// ========== 配置快照（切换失败时回滚） ==========

/// 单个被快照文件的内容与权限 mode
struct SnapshotFile {
    content: Vec<u8>,
    mode: u32,
}

/// 配置快照：保存一组文件内容和 systemd 服务状态，用于切换失败时恢复原状
pub struct ConfigSnapshot {
    files: HashMap<String, Option<SnapshotFile>>, // path -> file（None = 文件不存在）
    services: HashMap<String, Option<bool>>, // service -> is-enabled（None = 未知/未安装）
}

impl ConfigSnapshot {
    /// 保存指定路径列表的配置快照和服务状态
    pub fn save(paths: &[&str]) -> Result<Self, FtoolError> {
        let mut files = HashMap::new();
        for &path in paths {
            let entry = if Path::new(path).exists() {
                let metadata = fs::metadata(path).map_err(|e| {
                    FtoolError::Gpu(format!("读取快照文件元数据失败 {}: {}", path, e))
                })?;
                let content = fs::read(path).map_err(|e| {
                    FtoolError::Gpu(format!("读取快照文件失败 {}: {}", path, e))
                })?;
                let mode = metadata.permissions().mode();
                Some(SnapshotFile { content, mode })
            } else {
                None
            };
            files.insert(path.to_string(), entry);
        }
        debug!("已保存 {} 个文件的配置快照", files.len());

        let mut services = HashMap::new();
        for svc in SERVICE_SNAPSHOT_NAMES {
            services.insert(svc.to_string(), service_is_enabled(svc));
        }
        debug!("已保存 {} 个服务的状态快照", services.len());

        Ok(Self { files, services })
    }

    /// 将配置恢复到快照状态：先恢复文件，再恢复服务
    pub fn restore(&self) {
        info!("正在恢复配置快照...");

        for (path, file) in &self.files {
            match file {
                Some(file) => {
                    let executable = file.mode & 0o111 != 0;
                    match write_file_atomic(path, &file.content, executable) {
                        Ok(()) => {
                            if let Err(e) = fs::set_permissions(
                                path,
                                fs::Permissions::from_mode(file.mode),
                            ) {
                                warn!("回滚文件 {} 后恢复权限失败: {}", path, e);
                            }
                            debug!("已回滚文件: {}", path);
                        }
                        Err(e) => warn!("回滚文件 {} 失败: {}", path, e),
                    }
                }
                None => {
                    if let Err(e) = fs::remove_file(path)
                        && e.kind() != std::io::ErrorKind::NotFound
                    {
                        warn!("回滚时删除 {} 失败: {}", path, e);
                    }
                }
            }
        }

        for (svc, prev_state) in &self.services {
            match prev_state {
                Some(true) => {
                    if let Err(e) = toggle_service(svc, true) {
                        warn!("回滚服务 {} (enable) 失败: {}", svc, e);
                    }
                }
                Some(false) => {
                    if let Err(e) = toggle_service(svc, false) {
                        warn!("回滚服务 {} (disable) 失败: {}", svc, e);
                    }
                }
                None => {
                    debug!("跳过服务 {} 的回滚（快照时状态未知）", svc);
                }
            }
        }

        info!("配置快照恢复完成");
    }
}
