//! 挂起/休眠电源管理配置文件（modprobe 参数）的合并与写入。
//!
//! S0ix 与 S3 两套参数互斥且不可并存，切换挂起模式或重复写入时必须
//! 剔除残留参数行；合并逻辑由纯函数 `build_sleep_config_content` 承担。

use super::GpuMode;
use super::file_io::create_file;
use crate::core::FtoolError;
use crate::features::gpu::constants::*;
use crate::features::gpu::detector::{GpuDetector, SleepMode};
use log::{debug, warn};
use std::fs;

/// 计算挂起电源管理参数合并后的目标文件内容（纯函数，便于测试）。
///
/// 返回 `Some(content)` 表示需要写入（目标内容与 `existing` 不同），`None`
/// 表示文件已是最新、无需写入。规则：
/// - 剔除另一挂起模式（S0ix/S3 互斥）的参数残留行；
/// - 当前模式参数行已存在时保持剔除后的内容不变（幂等）；
/// - 缺少参数行时补写参数行，并确保 ftool 生成标记头存在且不重复。
fn build_sleep_config_content(
    existing: &str,
    sleep_text: &str,
    key_line: &str,
    other_key: &str,
) -> Option<String> {
    // 剔除另一挂起模式的参数行（S0ix/S3 参数不可并存）
    let lines: Vec<&str> = existing
        .lines()
        .filter(|l| !l.contains(other_key))
        .collect();

    // 幂等判断只认非注释的参数行，避免注释等相似文本误判为已配置
    let has_key = lines
        .iter()
        .any(|l| !l.trim_start().starts_with('#') && l.contains(key_line));

    let mut merged = String::new();
    if !has_key {
        if !lines.iter().any(|l| l.trim() == FTOOL_MARKER) {
            merged.push_str(FTOOL_MARKER);
            merged.push('\n');
        }
        for l in &lines {
            merged.push_str(l.trim_end());
            merged.push('\n');
        }
        merged.push_str(sleep_text.trim());
        merged.push('\n');
    } else {
        merged = lines.join("\n");
        if !merged.ends_with('\n') {
            merged.push('\n');
        }
    }

    (merged != existing).then_some(merged)
}

/// 根据系统挂起模式，追加对应的 NVIDIA 电源管理配置
///
/// Integrated 模式下此函数为 no-op（不写入任何睡眠配置）。
/// 其他模式通过"读现有内容 → 合并 → 原子写"的方式写入，
/// 确保写入操作整体原子性，避免在追加写入时若崩溃导致文件损坏。
pub(super) fn append_sleep_config(mode: GpuMode) -> Result<(), FtoolError> {
    if mode == GpuMode::Integrated {
        return Ok(());
    }

    let sleep_mode = GpuDetector::detect_sleep_mode();
    let sleep_content = match sleep_mode {
        SleepMode::S0ix => MODPROBE_S0IX,
        SleepMode::S3 => MODPROBE_S3,
        SleepMode::Unknown => {
            warn!("无法检测系统休眠模式，跳过挂起配置");
            return Ok(());
        }
    };

    let path = MODPROBE_GPU_PATH;

    // 用关键行做精确检查，避免因空白/顺序差异误判
    let (key_line, other_key) = match sleep_mode {
        SleepMode::S0ix => (
            "NVreg_EnableS0ixPowerManagement=1",
            "NVreg_PreserveVideoMemoryAllocations=1",
        ),
        SleepMode::S3 => (
            "NVreg_PreserveVideoMemoryAllocations=1",
            "NVreg_EnableS0ixPowerManagement=1",
        ),
        SleepMode::Unknown => unreachable!("Unknown 已在前面返回"),
    };

    // 读取现有内容（文件可能不存在）
    let existing = fs::read_to_string(path).unwrap_or_default();
    let sleep_text = String::from_utf8_lossy(sleep_content);
    // 目标内容由纯函数计算（剔除另一挂起模式残留、补写参数、幂等判断），
    // 与磁盘当前内容不同才原子写入
    if let Some(merged) = build_sleep_config_content(&existing, &sleep_text, key_line, other_key) {
        create_file(path, &merged, false)?;
    } else {
        debug!("挂起配置已是最新，跳过写入");
    }

    // 注意：本函数只负责写入挂起参数，不管理 NVIDIA 挂起服务的启停——
    // 服务状态统一由 mod.rs 的 configure_gpu_services 按模式决定
    // （各模式的启停策略见 mod.rs 中 configure_gpu_services 的调用点），避免此处无条件启用与模式策略相矛盾。

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::build_sleep_config_content;

    // ---------- 挂起配置内容合并 ----------

    const S0IX_KEY: &str = "NVreg_EnableS0ixPowerManagement=1";
    const S3_KEY: &str = "NVreg_PreserveVideoMemoryAllocations=1";
    const S0IX_TEXT: &str = "options nvidia NVreg_EnableS0ixPowerManagement=1";
    const S3_TEXT: &str = "options nvidia NVreg_PreserveVideoMemoryAllocations=1";
    const HEADER: &str = "# Automatically generated by ftool";

    #[test]
    fn sleep_config_empty_file_gets_header_and_params() {
        let out = build_sleep_config_content("", S0IX_TEXT, S0IX_KEY, S3_KEY).unwrap();
        assert!(out.starts_with(&format!("{HEADER}\n")));
        assert!(out.contains(S0IX_TEXT));
    }

    #[test]
    fn sleep_config_already_current_returns_none() {
        let current = format!("{HEADER}\n{S0IX_TEXT}\n");
        assert_eq!(
            build_sleep_config_content(&current, S0IX_TEXT, S0IX_KEY, S3_KEY),
            None
        );
    }

    #[test]
    fn sleep_config_other_mode_residue_is_stripped() {
        // 同一文件同时存在两种模式的参数（用户手写/旧版本遗留）：剔除另一模式残留
        let existing = format!("{HEADER}\n{S3_TEXT}\n{S0IX_TEXT}\n");
        let out = build_sleep_config_content(&existing, S0IX_TEXT, S0IX_KEY, S3_KEY).unwrap();
        assert!(!out.contains(S3_TEXT));
        assert!(out.contains(S0IX_KEY));
        // key 已存在：不重复追加 sleep_text 参数行
        assert_eq!(out.matches(S0IX_TEXT).count(), 1);
    }

    #[test]
    fn sleep_config_key_in_comment_is_not_treated_as_configured() {
        // key 文本只出现在注释行：不算已配置，仍需写入真实参数行
        let existing = format!("{HEADER}\n# 相关参数见 {S0IX_KEY}\n");
        let out = build_sleep_config_content(&existing, S0IX_TEXT, S0IX_KEY, S3_KEY).unwrap();
        assert!(out.contains(S0IX_TEXT));
    }

    #[test]
    fn sleep_config_header_not_duplicated() {
        // 已有其它用户内容但缺参数行：补写参数，标记头只保留一个
        let existing = format!("{HEADER}\noptions nvidia NVreg_UsePageAttributeTable=1\n");
        let out = build_sleep_config_content(&existing, S0IX_TEXT, S0IX_KEY, S3_KEY).unwrap();
        assert_eq!(out.matches(HEADER).count(), 1);
        assert!(out.contains(S0IX_TEXT));
        assert!(out.contains("NVreg_UsePageAttributeTable=1"));
    }

    #[test]
    fn sleep_config_switching_mode_strips_previous_params() {
        // 从 S0ix 切到 S3：existing 含 S0ix 参数行，应被剔除后写入 S3 参数
        let existing = format!("{HEADER}\n{S0IX_TEXT}\n");
        let out = build_sleep_config_content(&existing, S3_TEXT, S3_KEY, S0IX_KEY).unwrap();
        assert!(!out.contains(S0IX_KEY));
        assert!(out.contains(S3_TEXT));
    }
}
